//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QueryBuilderMVC.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose language.
        /// </summary>
        public static string ChooseLang {
            get {
                return ResourceManager.GetString("ChooseLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database Name:.
        /// </summary>
        public static string CreateConnectionDatabase {
            get {
                return ResourceManager.GetString("CreateConnectionDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection:.
        /// </summary>
        public static string CreateConnectionName {
            get {
                return ResourceManager.GetString("CreateConnectionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description:.
        /// </summary>
        public static string CreateProjectDescription {
            get {
                return ResourceManager.GetString("CreateProjectDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name project:.
        /// </summary>
        public static string CreateProjectName {
            get {
                return ResourceManager.GetString("CreateProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query body .
        /// </summary>
        public static string CreateQueryBody {
            get {
                return ResourceManager.GetString("CreateQueryBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query name.
        /// </summary>
        public static string CreateQueryName {
            get {
                return ResourceManager.GetString("CreateQueryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want delete this connection?.
        /// </summary>
        public static string DeleteConnectionQuestion {
            get {
                return ResourceManager.GetString("DeleteConnectionQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want delete this project?.
        /// </summary>
        public static string DeleteProjectQuestion {
            get {
                return ResourceManager.GetString("DeleteProjectQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want delete this query?.
        /// </summary>
        public static string DeleteQueryQuestion {
            get {
                return ResourceManager.GetString("DeleteQueryQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start FREE.
        /// </summary>
        public static string IndexStartFREE {
            get {
                return ResourceManager.GetString("IndexStartFREE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have the opportunity to see.
        /// </summary>
        public static string IndexTextAboutErModel1 {
            get {
                return ResourceManager.GetString("IndexTextAboutErModel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a detailed ER-model of your database..
        /// </summary>
        public static string IndexTextAboutErModel2 {
            get {
                return ResourceManager.GetString("IndexTextAboutErModel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your data will be save to popular format.
        /// </summary>
        public static string IndexTextAboutExportData1 {
            get {
                return ResourceManager.GetString("IndexTextAboutExportData1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to files on your PC or send to e-mail..
        /// </summary>
        public static string IndexTextAboutExportData2 {
            get {
                return ResourceManager.GetString("IndexTextAboutExportData2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have the ability to share your project with.
        /// </summary>
        public static string IndexTextAboutShared1 {
            get {
                return ResourceManager.GetString("IndexTextAboutShared1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to colleagues and build queries together or just give.
        /// </summary>
        public static string IndexTextAboutShared2 {
            get {
                return ResourceManager.GetString("IndexTextAboutShared2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to someone access requests in your project..
        /// </summary>
        public static string IndexTextAboutShared3 {
            get {
                return ResourceManager.GetString("IndexTextAboutShared3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AND EXCEL.
        /// </summary>
        public static string IndexTextAndExcel {
            get {
                return ResourceManager.GetString("IndexTextAndExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build query.
        /// </summary>
        public static string IndexTextBuildQuery {
            get {
                return ResourceManager.GetString("IndexTextBuildQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ability to build your requests only with the mouse. You do not need to know the SQL to build your query and get results. For this will be enough to use our intuitive graphical interface..
        /// </summary>
        public static string IndexTextBuildQueryText {
            get {
                return ResourceManager.GetString("IndexTextBuildQueryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DATABASE.
        /// </summary>
        public static string IndexTextDATABASE {
            get {
                return ResourceManager.GetString("IndexTextDATABASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ER-model your database.
        /// </summary>
        public static string IndexTextER {
            get {
                return ResourceManager.GetString("IndexTextER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ER-MODEL.
        /// </summary>
        public static string IndexTextErModel {
            get {
                return ResourceManager.GetString("IndexTextErModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have the opportunity to see a detailed ER-model of your database. The ER-model will help you to trace all the connections and relationships of tables, as well as the available fields..
        /// </summary>
        public static string IndexTextERText {
            get {
                return ResourceManager.GetString("IndexTextERText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXPORT DATA.
        /// </summary>
        public static string IndexTextEXPORTDATA {
            get {
                return ResourceManager.GetString("IndexTextEXPORTDATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export data.
        /// </summary>
        public static string IndexTextExportDataSmall {
            get {
                return ResourceManager.GetString("IndexTextExportDataSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opportunity to export result for your query in *.XLS and *.PDF. Your data will be save to popular format files on your PC or send to e-mail..
        /// </summary>
        public static string IndexTextExportDataText {
            get {
                return ResourceManager.GetString("IndexTextExportDataText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting started.
        /// </summary>
        public static string IndexTextGettingStarted {
            get {
                return ResourceManager.GetString("IndexTextGettingStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query Builder can use without registration. For use just press &quot;START FREE&quot;. Query Builder without registration have features such us:.
        /// </summary>
        public static string IndexTextGettinStartedText {
            get {
                return ResourceManager.GetString("IndexTextGettinStartedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More ».
        /// </summary>
        public static string IndexTextMore {
            get {
                return ResourceManager.GetString("IndexTextMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PROJECT.
        /// </summary>
        public static string IndexTextProject {
            get {
                return ResourceManager.GetString("IndexTextProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Different types of queries.
        /// </summary>
        public static string IndexTextQueries {
            get {
                return ResourceManager.GetString("IndexTextQueries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ability to build various types of queries, requests and combine to make nested queries.Complex queries are now easy to build..
        /// </summary>
        public static string IndexTextQueriesText {
            get {
                return ResourceManager.GetString("IndexTextQueriesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SHARED.
        /// </summary>
        public static string IndexTextShared {
            get {
                return ResourceManager.GetString("IndexTextShared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shared project.
        /// </summary>
        public static string IndexTextSharedProject {
            get {
                return ResourceManager.GetString("IndexTextSharedProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have the ability to share your project with colleagues and build queries together or just give someone access requests in your project..
        /// </summary>
        public static string IndexTextSharedProjectText {
            get {
                return ResourceManager.GetString("IndexTextSharedProjectText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to PDF.
        /// </summary>
        public static string IndexTextToPDF {
            get {
                return ResourceManager.GetString("IndexTextToPDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to SQLQueryBuilder.
        /// </summary>
        public static string IndexTextWelcome {
            get {
                return ResourceManager.GetString("IndexTextWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YOUR.
        /// </summary>
        public static string IndexTextYOUR {
            get {
                return ResourceManager.GetString("IndexTextYOUR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Page.
        /// </summary>
        public static string IndexTitle {
            get {
                return ResourceManager.GetString("IndexTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users for shared.
        /// </summary>
        public static string InviteUserTitle {
            get {
                return ResourceManager.GetString("InviteUserTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string LanguageEnglish {
            get {
                return ResourceManager.GetString("LanguageEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Russian.
        /// </summary>
        public static string LanguageRussian {
            get {
                return ResourceManager.GetString("LanguageRussian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ukrainian.
        /// </summary>
        public static string LanguageUkrainian {
            get {
                return ResourceManager.GetString("LanguageUkrainian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string LayoutAbout {
            get {
                return ResourceManager.GetString("LayoutAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string LayoutContact {
            get {
                return ResourceManager.GetString("LayoutContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string LayoutHome {
            get {
                return ResourceManager.GetString("LayoutHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - QueryBuilder.
        /// </summary>
        public static string LayoutTitle {
            get {
                return ResourceManager.GetString("LayoutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My connections.
        /// </summary>
        public static string ListMyConnection {
            get {
                return ResourceManager.GetString("ListMyConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query.
        /// </summary>
        public static string ListQuery {
            get {
                return ResourceManager.GetString("ListQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QueryBuilder.
        /// </summary>
        public static string ListQueryBuilder {
            get {
                return ResourceManager.GetString("ListQueryBuilder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string ListQuerySettings {
            get {
                return ResourceManager.GetString("ListQuerySettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result query.
        /// </summary>
        public static string ListResultQuery {
            get {
                return ResourceManager.GetString("ListResultQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello.
        /// </summary>
        public static string LoginPartialHello {
            get {
                return ResourceManager.GetString("LoginPartialHello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password must be at least 6 characters long..
        /// </summary>
        public static string ManageViewModelValidPassord {
            get {
                return ResourceManager.GetString("ManageViewModelValidPassord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        public static string ManageViewModelValidPasswordText {
            get {
                return ResourceManager.GetString("ManageViewModelValidPasswordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string ProjectName {
            get {
                return ResourceManager.GetString("ProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter project name.
        /// </summary>
        public static string ProjectValidationMessage {
            get {
                return ResourceManager.GetString("ProjectValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter description.
        /// </summary>
        public static string ProjectValidationMessageDescription {
            get {
                return ResourceManager.GetString("ProjectValidationMessageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limit length string for 150 symbols.
        /// </summary>
        public static string ProjectValidationMessageDescriptionMaxLenght {
            get {
                return ResourceManager.GetString("ProjectValidationMessageDescriptionMaxLenght", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limit length string for 16 letters.
        /// </summary>
        public static string ProjectValidationMessageMaxLenght {
            get {
                return ResourceManager.GetString("ProjectValidationMessageMaxLenght", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings .
        /// </summary>
        public static string SettingsForMenu {
            get {
                return ResourceManager.GetString("SettingsForMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose as current project.
        /// </summary>
        public static string TooltipCurrentProject {
            get {
                return ResourceManager.GetString("TooltipCurrentProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete this project.
        /// </summary>
        public static string TooltipDeleteProject {
            get {
                return ResourceManager.GetString("TooltipDeleteProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit this project.
        /// </summary>
        public static string TooltipEditProject {
            get {
                return ResourceManager.GetString("TooltipEditProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shared this project your colleges.
        /// </summary>
        public static string TooltipInviteProject {
            get {
                return ResourceManager.GetString("TooltipInviteProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select user.
        /// </summary>
        public static string UserViewModelUser {
            get {
                return ResourceManager.GetString("UserViewModelUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string WorkflowLogIn {
            get {
                return ResourceManager.GetString("WorkflowLogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Off.
        /// </summary>
        public static string WorkflowLogOff {
            get {
                return ResourceManager.GetString("WorkflowLogOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Settings.
        /// </summary>
        public static string WorkflowMenuSettings {
            get {
                return ResourceManager.GetString("WorkflowMenuSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new project.
        /// </summary>
        public static string WorkflowNewProject {
            get {
                return ResourceManager.GetString("WorkflowNewProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string WorkflowRegister {
            get {
                return ResourceManager.GetString("WorkflowRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings account.
        /// </summary>
        public static string WorkflowSettingAccount {
            get {
                return ResourceManager.GetString("WorkflowSettingAccount", resourceCulture);
            }
        }
    }
}
